language: python
dist: trusty
sudo: false

python:
- "2.7"
- "3.5"
- "3.6"

before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
  
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes
- conda update -q conda
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy
- source activate test-environment
- conda install -q pip openblas numpy scipy pandas keras
- "pip install -q nose"
- "pip install coverage"
- "pip install mcfly"

install:
- "echo done"

# command to run tests, e.g. python setup.py test
script:
- nosetests --with-coverage --cover-package=mcfly-tutorial

after_script:
- "pip install scrutinizer-ocular"
- "ocular"
